version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  redis:
    image: 'bitnami/redis:latest'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"

  keycloak:
    image: docker.io/bitnami/keycloak:18
    depends_on:
      - postgresql
      - redis
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
    driver: local
