version: '2'
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=postgres
      - POSTGRES_DB=public
      - POSTGRES_PASSWORD=ASDqwe123!@#
    volumes:
      - 'postgresql_data:/postgres'
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ASDqwe123!@#
    ports:
      - "5050:80"

volumes:
  postgresql_data:
    driver: local
